battery: 
  capacity_kwh: 1000    # Battery capacity in MWh
  max_charge_kw: 5      # Maximum charge rate
  max_discharge_kw: 5 # Maximum discharge rate
  efficiency: 0.97   # Efficiency of charge/discharge
  soc_init: 0.1 # State of Charge (SOC) initial value
  degradation_rate: 0.001 # per cycle


